[badges.travis-ci]
repository = "alexcrichton/toml-rs"

[dependencies]
serde = "1.0"

[dev-dependencies]
new-key = "4.888"
serde_derive = "1.0"
serde_json = "1.0"

[package]
authors = ["Alex Crichton <alex@alexcrichton.com>"]
name = "toml"
version = "0.4.5"
