[package]
name = "md5sum"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
md-5 = "0.7.0"
#crypto = "0.4.0"
rust-crypto = "0.2.36"
hex = "0.4.3"